version: '3.8'
services:
  api_rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices_breakfast_network
  
  kitchen:
    container_name: kitchen_service
    build:
      context: ./kitchen
      dockerfile: Dockerfile
      target: prod
    restart: always
    env_file: ./kitchen/.env
    ports:
      - "3001:3001"
    depends_on:
      - kitchen_db
      - api_rabbitmq
    command: npm start
    networks:
      - microservices_breakfast_network
  
  kitchen_db:
    image: mysql:9.4-oraclelinux9
    container_name: kitchen_db_container
    restart: always
    volumes:
      - ./kitchen/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: ./kitchen/.env.db
    networks:
      - microservices_breakfast_network

  warehouse:
    container_name: warehouse_service
    build:
      context: ./warehouse
      dockerfile: Dockerfile
      target: prod
    restart: always
    env_file: ./warehouse/.env
    ports:
      - "3002:3002"
    depends_on:
      - warehouse_db
      - api_rabbitmq
    command: npm start
    networks:
      - microservices_breakfast_network

  warehouse_db:
    image: mysql:9.4-oraclelinux9
    container_name: warehouse_db_container
    restart: always
    volumes:
      - ./warehouse/mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file: ./warehouse/.env.db
    networks:
      - microservices_breakfast_network

  market:
    container_name: market_service
    build:
      context: ./market
      dockerfile: Dockerfile
      target: prod
    restart: always
    env_file: ./market/.env
    ports:
      - "3003:3003"
    depends_on:
      - market_db
      - api_rabbitmq
    command: npm start
    networks:
      - microservices_breakfast_network

  market_db:
    image: mysql:9.4-oraclelinux9
    container_name: market_db_container
    restart: always
    volumes:
      - ./market/mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    env_file: ./market/.env.db
    networks:
      - microservices_breakfast_network

networks:
  microservices_breakfast_network:
    driver: bridge
